modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"

[[mods]]
    modId = "${mod_id}"
    version = "${mod_version}"
    displayName = "Mekanism: MoreMachine"
    # A URL to query for updates for this mod. See the JSON update specification https://docs.neoforge.net/docs/misc/updatechecker/
    #updateJSONURL="https://change.me.example.invalid/updates.json" #optional
    displayURL= "https://www.curseforge.com/members/lost_myself8/projects"
    logoFile= "logo.png"
    # A text field displayed in the mod UI
    credits="Thank you to all those who have made any contributions to this mod" #optional
    # A text field displayed in the mod UI
    authors = "${mod_authors}" #optional
    # The description text for the mod (multi line!) (#mandatory)
    description = '''${mod_description}'''

[[mixins]]
    config = "${mod_id}.mixins.json"

[[dependencies."${mod_id}"]]
    modId = "neoforge"
    type = "required"
    versionRange = "${neo_version_range}"
    ordering = "NONE"
    side = "BOTH"

[[dependencies."${mod_id}"]]
    modId = "minecraft"
    type = "required"
    versionRange = "${minecraft_version_range}"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.${mod_id}]]
    modId = "mekanism"
    type = "required"
    versionRange = "[10.7.15]"
    ordering = "AFTER"
    side = "BOTH"
